name: Run Builds

on: workflow_dispatch

jobs:
  windows_build:
    uses: coyoteclan/warzone2003-website/.github/workflows/build-win-setup.yml@main

  linux_build:
    needs: windows_build
    uses: coyoteclan/warzone2003-website/.github/workflows/build-linux-setup.yml@main
