name: Build Windows Setup

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Deps
        shell: bash
        run: |
          sudo snap remove firefox
          sudo apt purge snap*
          sudo rm -f /etc/apt/sources.list.d/{azure,microsoft}*
          sudo apt update
          sudo apt install nasm build-essential pkg-config git rustup gcc-mingw-w64-i686 -y
          rustup default stable
          rustup target add i686-pc-windows-gnu

      - name: Clone Warzone 2003 Setup Repo
        run: |
          git clone https://gitlab.com/kazam0180/warzone2003setup.git

      - name: Compile and Copy
        run: |
          cd warzone2003setup
          cargo build --release --target i686-pc-windows-gnu
          git fetch --tags
          export VERSION="$(git tag --list | sort -V | tail -n1)"
          echo $VERSION
          cp target/i686-pc-windows-gnu/release/warzone2003setup.exe ./warzone2003setup-$VERSION-windows.exe
          # p7zip warzone2003setup-$VERSION-windows.exe
          mv ./warzone2003setup-$VERSION-windows.exe ../files/
          cd ..
          rm -rf warzone2003setup

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add files
          git commit -m "chore: upload warzone2003setup windows binary" || echo "No changes to commit"
          git push
